name: sentra
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  searchfield: ^0.6.5
  flutter_slidable: ^1.3.0
  google_fonts: ^3.0.1
  splash_screen_view: ^3.0.0
  image_picker: ^0.8.5+3
  equatable: ^2.0.3
  dartz: ^0.10.1
  flutter_bloc: ^8.0.1
  bloc_test: ^9.0.3
  rxdart: ^0.27.4
  get_it: ^7.2.0
  path_provider: ^2.0.11
  http: ^0.13.4
  provider: ^6.0.3
  cached_network_image: ^3.2.1
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  sqflite: ^2.0.2+1
  readmore: ^2.2.0
  connectivity: ^3.0.6
  flutter_offline: ^2.1.0
  shared_preferences: ^2.0.15
  android_alarm_manager_plus: ^2.0.6
  intl: ^0.17.0
  flutter_local_notifications: ^9.6.1
  modal_progress_hud_nsn: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/seni/
    - assets/logo/
    - assets/dummy_data/
    - images/